# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tX83aRl45IeApOzD_Q8QuOb8rmfRQlI
"""

f = open("demo.py", "r")
print(f.read())

x = open("demo.py", "r")
print(x.read(2))

x = open("demo.py", "r")
print(x.readline())
print(x.readline())
print(x.readline())
print(x.readline())
print(x.readline())

x = open("demo.py", "r")
for y in x:
   print(y)

y = open("demo.py", "r")
print(y.readline())
y.close()

f = open("demo.py", "a")
f.write("Now the file has more content")
f.close()
f = open("demo.py,", "r")
print(f.read())

f = open("demo.py", "w")
f.write("woop I have deleated the contrent")
f.close()
f = open("demo.py", "r")
print(f.read())

f = open("demo.py", "w")

import os
if os.path.exists("demo.py"):
   os.remove("demo.py")
else:
   print("The file does not exist")

