# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xic3QsZjjsZWeMnF6MocVCdxu9xdigQG
"""

def fact(n):
  return 1 if (n==1 or n==0) else n * fact(n - 1)

num = 5
print("factorial of",num,"is",fact(num))



"""factorial

"""

def factorial(n):
  if n < 0:
    return 0
  elif n == 0 or n == 1:
    return 1
  else:
      fact = 1
      while(n > 1):
        fact *= n
        n -= 1
      return fact
fact = 5
print("factorial   of",num,"is",factorial(num))

def fact(n):
  res = 1
  for i in range(2, n+1):
    res *= i
  return res
num = 5
print("factorial of", num, "is", fact(num))

import math
def fact(n):
    return(math.factorial(n))

num = 4
print("Factorial of", num, "is",fact(num))

import numpy
n = int(input("Enter The Number"))
x=numpy.prod([i for i in range(1,n+1)])
print(x)

"""Simple Interest"""

def simple_interest(p,t,r):
   print('The Principal is', p)
   print("The time period is", t)
   print("The rate of interest is", r)

   x  = (p * t * r)/100
   print("The Simple Interst is", x)

   return x
simple_interest(8,7,9)

def simple_interest(p,t,r):
   #print('The Principal is', p)
   #print("The time period is", t)
  # print("The rate of interest is", r)
   print(p, t, r)
   x  = (p * t * r)/100
   print("The Simple Interst is", x)
p = int(input("Enter The P Number :"))
t = int(input("Enter The t Number :"))
r = int(input("Enter The r Number :"))
simple_interest(p,t,r)

